---
- name: restart node_exporter
  service:
    name: node_exporter
    state: restarted
  tags:
    - prometheus
    - node_exporter

- name: systemd reload
  systemd:
    daemon_reload: yes
  tags:
    - prometheus
    - node_exporter
...
